name: codecov generate
on: [pull_request]
jobs:
  run:
    runs-on: ubuntu-18.04

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2.3.1

      - name: install yarn dependencies in app/client using cache
        uses: bahmutov/npm-install@v1.6.0
        with:
          working-directory: ./app/client

      - name: install yarn dependencies in ./ using cache
        uses: bahmutov/npm-install@v1.6.0
        with:
          working-directory: ./

      - name: install yarn dependencies in ./app using cache
        uses: bahmutov/npm-install@v1.6.0
        with:
          working-directory: ./app

      - name: yarn build
        run: yarn build

      - name: yarn test
        run: yarn test

      - name: yarn coverage
        run: yarn coverage

      - name: Upload app coverage to Codecov
        uses: codecov/codecov-action@v1.0.12
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/clover.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true

      - name: Upload app/client coverage to Codecov
        uses: codecov/codecov-action@v1.0.12
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./app/client/coverage/clover.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
