name: build and test

on: [pull_request]

# NPMRC_ADMIN_USER_AUTH_TOKEN

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-10.15, windows-2019, ubuntu-18.04]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2.3.1

      - name: install yarn dependencies in app/client using cache
        uses: bahmutov/npm-install@v1.6.0
        with:
          working-directory: ./app/client

      - name: install yarn dependencies in ./ using cache
        uses: bahmutov/npm-install@v1.6.0
        with:
          working-directory: ./

      - name: install yarn dependencies in ./app using cache
        uses: bahmutov/npm-install@v1.6.0
        with:
          working-directory: ./app

      # following step does code signing when `electron-builder --publish always` (look in package.json)
      - name: yarn package-ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn package-ci

      - name: yarn build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn build

      - name: yarn lint
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn lint

      - name: yarn tsc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn tsc

      - name: yarn test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn test

      - name: yarn build-ux
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn build-ux

      - name: yarn test-ux
        uses: GabrielBB/xvfb-action@v1.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          run: yarn test-ux
